[build]
  # No build command needed for static HTML
  command = ""
  # Publish the root directory
  publish = ""

# Redirect rules for better SEO
[[redirects]]
  from = "/article"
  to = "/DevOps_Article.pdf"
  status = 301

[[redirects]]
  from = "/pdf"
  to = "/DevOps_Article.pdf"
  status = 301

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
